# ... existing code ...
def validate_password(pwd):
    has_cap = any(c.isupper() for c in pwd)
    has_low = any(c.islower() for c in pwd)
    has_num = any(c.isdigit() for c in pwd)
    has_spec = any(not c.isalnum() for c in pwd)
    return has_cap and has_low and has_num and has_spec

def display_pdf(file_name, start_page, end_page):
    """Extracts specific pages from a PDF and embeds them as a standalone document."""
    import fitz # PyMuPDF
    file_path = os.path.join("casebooks", file_name)
    if os.path.exists(file_path):
        try:
            # Open original PDF
            doc = fitz.open(file_path)
            # Start and end pages are 1-indexed in the CSV, convert to 0-indexed
            start_idx = max(0, int(start_page) - 1)
            end_idx = min(len(doc) - 1, int(end_page) - 1)
            
            # Create a new mini-PDF containing ONLY the pages for this case
            new_doc = fitz.open()
            new_doc.insert_pdf(doc, from_page=start_idx, to_page=end_idx)
            
            # Convert to base64 for Streamlit HTML embed
            pdf_bytes = new_doc.write()
            base64_pdf = base64.b64encode(pdf_bytes).decode('utf-8')
            
            pdf_display = f'<iframe src="data:application/pdf;base64,{base64_pdf}" width="100%" height="800px" type="application/pdf"></iframe>'
            st.markdown(pdf_display, unsafe_allow_html=True)
            
            new_doc.close()
            doc.close()
        except Exception as e:
            st.error(f"Error processing PDF slice: {e}")
    else:
        st.error(f"⚠️ PDF file '{file_name}' not found locally. Please ensure you have uploaded your PDFs to the 'casebooks' folder on GitHub.")

# --- AUTHENTICATION & ONBOARDING FLOW ---
if not st.session_state.logged_in_user:
# ... existing code ...
if 'active_behavioral_q' not in st.session_state:
    st.session_state.active_behavioral_q = "Tell me about a time when you managed conflict within a high-pressure team."
if 'admin_auth' not in st.session_state:
    st.session_state.admin_auth = False

if 'case_catalog' not in st.session_state:
    # Look for the CSV generated by the pdf_cataloger.py script
    if os.path.exists("case_catalog.csv"):
        st.session_state.case_catalog = pd.read_csv("case_catalog.csv")
    else:
        # Fallback catalog if CSV is missing
        st.session_state.case_catalog = pd.DataFrame([
            {"title": "Food Wholesaling Profitability", "source": "Kellogg 2011", "type": "Profitability", "difficulty": "Foundational", "pdf_file": "Kellogg_2011.pdf", "start_page": 4, "end_page": 10},
            {"title": "Canadian Mobile Banking App", "source": "Management Consulted", "type": "Market Entry", "difficulty": "Intermediate", "pdf_file": "Management_Consulted.pdf", "start_page": 12, "end_page": 18},
            {"title": "Radiator Co. European Acquisition", "source": "Wharton 2019", "type": "M&A", "difficulty": "Advanced", "pdf_file": "Wharton_2019.pdf", "start_page": 22, "end_page": 28},
        ])

# --- HELPER FUNCTIONS ---
# ... existing code ...
elif nav_selection == "Hub 2: Behavioral & Fit":
    st.title("Behavioral & Fit Hub")
    st.markdown("Master personal experience interviews using the P.A.R.T. and STAR frameworks.")

    st.subheader("Question Bank")
    questions = [
        "Tell me about a time when you managed conflict within a high-pressure team.",
        "Describe a situation where a project failed and your recovery strategy.",
        "Give an example of driving results under extremely tight deadlines.",
        "Tell me about a time you convinced a skeptical stakeholder to adopt your recommendation.",
        "What is your proudest professional accomplishment?"
    ]

    for q in questions:
        col_q1, col_q2 = st.columns([4, 1])
        with col_q1:
            st.markdown(f"• **{q}**")
        with col_q2:
            if st.button("Practice →", key=f"btn_{q}"):
                st.session_state.active_behavioral_q = q
                st.rerun()

    st.divider()
    st.subheader("🤖 Live AI Behavioral Answer Evaluator")
    st.info(f"**Active Question:** {st.session_state.active_behavioral_q}")

    user_api_key = st.text_input("🔗 Connect your OpenAI API Key", type="password", help="Your key is not saved and is only used to evaluate this response.")
    user_answer = st.text_area("Draft your response using the P.A.R.T. (Problem, Action, Result, Takeaway) framework:")
    
    if st.button("Evaluate Response via AI"):
        if not user_api_key.startswith("sk-"):
            st.error("Please provide a valid OpenAI API key to run the evaluation.")
        elif len(user_answer.strip()) < 20:
            st.warning("Please draft a complete response before evaluating.")
        else:
            with st.spinner("Consulting AI is analyzing your response..."):
                try:
                    client = OpenAI(api_key=user_api_key)
                    prompt = f"""
                    You are a rigorous MBB management consulting interviewer. 
                    The candidate was asked: "{st.session_state.active_behavioral_q}"
                    Their response: "{user_answer}"
                    
                    Evaluate their response using the P.A.R.T. (Problem, Action, Result, Takeaway) framework.
                    Provide:
                    1. A score out of 5.0 (e.g., Strong Hire, Borderline, No Hire).
                    2. Strengths (What they did well).
                    3. Areas to Refine (Actionable feedback for consulting readiness).
                    Keep it professional, direct, and concise.
                    """
                    
                    # Direct integration with the user's ChatGPT account
                    response = client.chat.completions.create(
                        model="gpt-4o-mini", # Highly cost efficient model
                        messages=[{"role": "user", "content": prompt}],
                        temperature=0.7
                    )
                    
                    st.success("Evaluation Complete")
                    st.markdown("### AI Interviewer Feedback")
                    st.write(response.choices[0].message.content)
                except Exception as e:
                    st.error(f"Error connecting to OpenAI API: {str(e)}")

# ==========================================
# --- HUB 3: MASTER CASE BANK ---
# ... existing code ...
    for index, row in df_cases.iterrows():
        if (diff_filter == "All" or row['difficulty'] == diff_filter) and (type_filter == "All" or row['type'] == type_filter):
            with st.container():
                st.markdown(f"""
                <div class='card'>
                    <span style='background:#0d948820; color:#2dd4bf; padding:2px 8px; border-radius:6px; font-size:12px;'>{row['difficulty']}</span>
                    <span style='color:#94a3b8; font-size:12px; margin-left:10px;'>{row['source']} | {row['type']}</span>
                    <h3>{row['title']}</h3>
                </div>
                """, unsafe_allow_html=True)
                
                if st.button(f"Open Casebook PDF: {row['title']}", key=f"case_{index}"):
                    st.markdown("---")
                    st.markdown(f"### 📖 Viewer: {row['title']} ({row['source']})")
                    # Dynamically slices the PDF to show the full case range
                    display_pdf(row['pdf_file'], row['start_page'], row['end_page'])
                    st.markdown("---")

# ==========================================
# --- JOB SEARCH TRACKER ---
# ... existing code ...